spring:
  application:
    name: TP API


  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: apihackr@gmail.com
    password: ztzo vvgu ssnc kxme
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp

  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8081/resource-server
        client:
          token-standard:
            registration:
              client-id: clientIdTpApiStandard
              client-secret: clientSecretTpApiStandard
              client-name: Auth TP Api Standard
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - client_credentials
              redirect-uris: []
          token-admin:
            registration:
              client-id: clientIdTpApiAdmin
              client-secret: clientSecretTpApiAdmin
              client-name: Auth TP Api Admin
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - client_credentials
              redirect-uris: [ ]

server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG
