spring:
  application:
    name: TP API

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp

  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8081/resource-server
        client:
          token-standard:
            registration:
              client-id: clientIdTpApiStandard
              client-secret: clientSecretTpApiStandard
              client-name: Auth TP Api Standard
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - client_credentials
              redirect-uris: []
          token-admin:
            registration:
              client-id: clientIdTpApiAdmin
              client-secret: clientSecretTpApiAdmin
              client-name: Auth TP Api Admin
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - client_credentials
              redirect-uris: []

server:
  port: 8081

hunter:
  url: ${HUNTER_URL}

securityTrail:
  url: https://api.securitytrails.com/v1/domain/
  apiKey: ${SECURITY_TRAIL_API_KEY}

thisPersonDoesNotExist:
  url: https://thispersondoesnotexist.com/

serpApi:
  apiKey: ${SERPAPI_API_KEY}

logging:
  level:
    org.springframework.security: DEBUG
